package com.example.fitnesstracker.workout

import com.example.fitnesstracker.R

data class WorkoutVariant(val id: String, val type: String, val labelRes: Int, val mode: EntryMode, val outdoor: Boolean = false)
data class ExercisePreset(val labelRes: Int, val mode: EntryMode)

object WorkoutCatalog {
    val variants = listOf(
        WorkoutVariant("free", "general", R.string.variant_free, EntryMode.REPS, false),
        WorkoutVariant("bodyweight", "general", R.string.variant_bodyweight, EntryMode.REPS, false),
        WorkoutVariant("functional", "general", R.string.variant_functional, EntryMode.REPS, false),
        WorkoutVariant("circuit", "general", R.string.variant_circuit, EntryMode.REPS, false),
        WorkoutVariant("elliptical", "general", R.string.variant_elliptical, EntryMode.TIME, false),
        WorkoutVariant("rowing", "general", R.string.variant_rowing, EntryMode.DISTANCE, false),
        WorkoutVariant("dance", "general", R.string.variant_dance, EntryMode.TIME, false),
        WorkoutVariant("mobility", "general", R.string.variant_mobility, EntryMode.TIME, false),
        WorkoutVariant("outdoor_run", "run", R.string.variant_outdoor_run, EntryMode.DISTANCE, true),
        WorkoutVariant("treadmill", "run", R.string.variant_treadmill, EntryMode.DISTANCE, false),
        WorkoutVariant("trail", "run", R.string.variant_trail, EntryMode.DISTANCE, true),
        WorkoutVariant("track", "run", R.string.variant_track, EntryMode.DISTANCE, true),
        WorkoutVariant("run_intervals", "run", R.string.variant_run_intervals, EntryMode.DISTANCE, true),
        WorkoutVariant("run_walk", "run", R.string.variant_run_walk, EntryMode.DISTANCE, true),
        WorkoutVariant("outdoor_walk", "walk", R.string.variant_outdoor_walk, EntryMode.DISTANCE, true),
        WorkoutVariant("hiking", "walk", R.string.variant_hiking, EntryMode.DISTANCE, true),
        WorkoutVariant("nordic", "walk", R.string.variant_nordic, EntryMode.DISTANCE, true),
        WorkoutVariant("walking_track", "walk", R.string.variant_walking_track, EntryMode.DISTANCE, true),
        WorkoutVariant("walking_treadmill", "walk", R.string.variant_walking_treadmill, EntryMode.DISTANCE, false),
        WorkoutVariant("indoor_walk", "walk", R.string.variant_indoor_walk, EntryMode.TIME, false),
        WorkoutVariant("road", "cycle", R.string.variant_road, EntryMode.DISTANCE, true),
        WorkoutVariant("city", "cycle", R.string.variant_city, EntryMode.DISTANCE, true),
        WorkoutVariant("gravel", "cycle", R.string.variant_gravel, EntryMode.DISTANCE, true),
        WorkoutVariant("mountain", "cycle", R.string.variant_mountain, EntryMode.DISTANCE, true),
        WorkoutVariant("stationary_bike", "cycle", R.string.variant_stationary_bike, EntryMode.DISTANCE, false),
        WorkoutVariant("spin", "cycle", R.string.variant_spin, EntryMode.TIME, false),
        WorkoutVariant("full_body", "gym", R.string.variant_full_body, EntryMode.REPS, false),
        WorkoutVariant("upper_body", "gym", R.string.variant_upper_body, EntryMode.REPS, false),
        WorkoutVariant("lower_body", "gym", R.string.variant_lower_body, EntryMode.REPS, false),
        WorkoutVariant("push", "gym", R.string.variant_push, EntryMode.REPS, false),
        WorkoutVariant("pull", "gym", R.string.variant_pull, EntryMode.REPS, false),
        WorkoutVariant("dumbbells", "gym", R.string.variant_dumbbells, EntryMode.REPS, false),
        WorkoutVariant("machines", "gym", R.string.variant_machines, EntryMode.REPS, false),
        WorkoutVariant("resistance_bands", "gym", R.string.variant_resistance_bands, EntryMode.REPS, false),
        WorkoutVariant("hatha", "yoga", R.string.variant_hatha, EntryMode.TIME, false),
        WorkoutVariant("vinyasa", "yoga", R.string.variant_vinyasa, EntryMode.TIME, false),
        WorkoutVariant("yin", "yoga", R.string.variant_yin, EntryMode.TIME, false),
        WorkoutVariant("restorative", "yoga", R.string.variant_restorative, EntryMode.TIME, false),
        WorkoutVariant("pilates", "yoga", R.string.variant_pilates, EntryMode.TIME, false),
        WorkoutVariant("stretching", "yoga", R.string.variant_stretching, EntryMode.TIME, false),
        WorkoutVariant("balance", "yoga", R.string.variant_balance, EntryMode.TIME, false),
        WorkoutVariant("tennis", "sport", R.string.variant_tennis, EntryMode.SCORE, false),
        WorkoutVariant("badminton", "sport", R.string.variant_badminton, EntryMode.SCORE, false),
        WorkoutVariant("table_tennis", "sport", R.string.variant_table_tennis, EntryMode.SCORE, false),
        WorkoutVariant("basketball", "sport", R.string.variant_basketball, EntryMode.SCORE, false),
        WorkoutVariant("football", "sport", R.string.variant_football, EntryMode.SCORE, false),
        WorkoutVariant("volleyball", "sport", R.string.variant_volleyball, EntryMode.SCORE, false),
        WorkoutVariant("swimming", "sport", R.string.variant_swimming, EntryMode.DISTANCE, false),
        WorkoutVariant("skating", "sport", R.string.variant_skating, EntryMode.DISTANCE, false)
    )
    val exercises = listOf(
        ExercisePreset(R.string.exercise_squat, EntryMode.REPS),
        ExercisePreset(R.string.exercise_push_up, EntryMode.REPS),
        ExercisePreset(R.string.exercise_pull_up, EntryMode.REPS),
        ExercisePreset(R.string.exercise_lunge, EntryMode.REPS),
        ExercisePreset(R.string.exercise_bench_press, EntryMode.REPS),
        ExercisePreset(R.string.exercise_dumbbell_press, EntryMode.REPS),
        ExercisePreset(R.string.exercise_overhead_press, EntryMode.REPS),
        ExercisePreset(R.string.exercise_cable_row, EntryMode.REPS),
        ExercisePreset(R.string.exercise_lat_pull, EntryMode.REPS),
        ExercisePreset(R.string.exercise_dumbbell_row, EntryMode.REPS),
        ExercisePreset(R.string.exercise_leg_press, EntryMode.REPS),
        ExercisePreset(R.string.exercise_leg_curl, EntryMode.REPS),
        ExercisePreset(R.string.exercise_biceps_curl, EntryMode.REPS),
        ExercisePreset(R.string.exercise_triceps_extension, EntryMode.REPS),
        ExercisePreset(R.string.exercise_calf_raise, EntryMode.REPS),
        ExercisePreset(R.string.exercise_bridge, EntryMode.REPS),
        ExercisePreset(R.string.exercise_plank, EntryMode.TIME),
        ExercisePreset(R.string.exercise_side_plank, EntryMode.TIME),
        ExercisePreset(R.string.exercise_tree_pose, EntryMode.TIME),
        ExercisePreset(R.string.exercise_child_pose, EntryMode.TIME),
        ExercisePreset(R.string.exercise_warrior_pose, EntryMode.TIME),
        ExercisePreset(R.string.exercise_down_dog, EntryMode.TIME),
        ExercisePreset(R.string.exercise_stretch, EntryMode.TIME),
        ExercisePreset(R.string.exercise_mobility_move, EntryMode.TIME),
        ExercisePreset(R.string.exercise_dance_round, EntryMode.TIME),
        ExercisePreset(R.string.exercise_elliptical_round, EntryMode.TIME),
        ExercisePreset(R.string.exercise_balance_hold, EntryMode.TIME),
        ExercisePreset(R.string.exercise_pilates_move, EntryMode.TIME),
        ExercisePreset(R.string.exercise_running_lap, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_walking_lap, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_cycling_lap, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_rowing_lap, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_freestyle, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_breaststroke, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_backstroke, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_swim_lap, EntryMode.DISTANCE),
        ExercisePreset(R.string.exercise_match, EntryMode.SCORE),
        ExercisePreset(R.string.exercise_game_set, EntryMode.SCORE),
        ExercisePreset(R.string.exercise_throws, EntryMode.SCORE),
        ExercisePreset(R.string.exercise_serves, EntryMode.SCORE),
        ExercisePreset(R.string.exercise_round, EntryMode.SCORE),
        ExercisePreset(R.string.exercise_practice_game, EntryMode.SCORE)
    )
    fun forType(type: String): List<WorkoutVariant> {
        val base = variants.filter { it.type == type }.ifEmpty { variants.filter { it.type == "general" } }
        return base + WorkoutVariant("${type}_custom", type, R.string.journal_custom, base.first().mode)
    }
    fun variant(plan: WorkoutPlan): WorkoutVariant = forType(plan.type).firstOrNull { it.id == plan.variantId } ?: forType(plan.type).first()
    fun initial(type: String) = WorkoutPlan(type = type, variantId = forType(type).first().id)
}
